#Sat Aug 01 15:36:56 COT 2026
analytics=false
language=java
lombok=true
metrics=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.integrity-check=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.read-only=false
org.gradle.parallel=true
package=io.github.ingcarlosgm.franchiseinventory
reactive=true
systemProp.sonar.gradle.skipCompile=true
systemProp.version=4.5.0
